name: MapStruct
title: Creating Bean Mappings the Easy Way
org: Gunnar Morling
base_url: ''
google_analytics: UA-41136939-1
google_analytics_anonymize: true

profiles:
  production:
    base_url: http://mapstruct.org
    deploy:
      host: github_pages
      branch: gh-pages
      repository: upstream
